[package]
name = "uring-sys"
version = "0.1.0"
authors = ["samgiles"]
edition = "2018"
license = "Apache 2.0"

[dependencies]
bitflags = "*"
static_assertions = "1.0.0"
libc = "*"

[dev-dependencies]
byteorder = "*"
